version: "3.9"
services:
  dev:
    image: "atk/{project}:dev"
    hostname: "{project}-dev"
    container_name: "{project}-dev"
    build:
      context: "{project_root}"
      dockerfile: "{atk_root}/docker/dev/dev.dockerfile"
      network: "host"
      args:
        PROJECT: "{project}"
        USERNAME: "{container_username}"
        SCRIPTS_DIR: "docker/dev/scripts"
        ROS_DISTRO: "galactic"
        ROS_WORKSPACE: "workspace"
        APT_DEPENDENCIES: ""
        PIP_REQUIREMENTS: ""
    environment:
      DISPLAY: vnc:0.0
      USER_UID: "{uid}"
      USER_GID: "{gid}"
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "all"
    tty: true
    working_dir: "/home/{container_username}/{project}/workspace"
    volumes: 
     - "{project_root}:/home/{container_username}/{project}"
  vnc:
    image: "atk/{project}:vnc"
    hostname: "{project}-vnc"
    container_name: "{project}-vnc"
    build:
      context: "{atk_root}/docker/vnc"
      dockerfile: "{atk_root}/docker/vnc/vnc.dockerfile"
      network: "host"
      args:
        VNC_PASSWORD: "{project}"
    environment:
      RUN_XTERM: no
      RUN_FLUXBOX: yes
    ports:
      - "8080:8080"
      - "5900:5900"
networks:
  default:
    name: "{project}"
